config/routes.rb
Wd::Application.routes.draw do
  resource :home
  devise_for :users

  resources :subjects do
    resources :comments
  end
  resources :notes
  resources :veil_passes, :users
  resource :searches
  resources :tags

  root :to => "homes#show"
end

app/models/note.rb
class Note < ActiveRecord::Base
  include Rails.application.routes.url_helpers

  has_permalink

  validates :name, uniqueness: true, presence: true, format: {with: /\A[a-z0-9]/i}
  validates :permalink, :uniqueness => true, :presence => true
  validates :text, :presence => true

  before_save :update_vp_text, :if => :text_changed?
  before_save :update_anon_text, :if => :text_changed?

  def to_param
    self.permalink
  end

  def url
    new_record? ? new_note_path(note: {name: name}) : url_for(self)
  end

  def authorized_users
    []
  end

  private


  def self.dummy(name)
    Subject.new(name: name)
  end

  def update_vp_text
    self.vp_text = DmStripper.strip(text, nil, true)
  end

  def update_anon_text
    self.anon_text = DmStripper.strip(text, nil, false)
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  load_resource :find_by => :permalink
  authorize_resource

  def create
    if @note.save
      redirect_to @note, notice: "Note created"
    else
      render :new
    end
  end

  def destroy
    @note.destroy
    redirect_to({action: "index"}, alert: "Note destroyed")
  end

  def index
    @notes = @notes.order("name ASC")
  end

  def update
    if @note.update(note_params)
      redirect_to @note, notice: "Note updated"
    else
      render :edit
    end
  end


  protected

  def note_params
    params
      .require(:note)
      .permit(:name, :text, :permalink, :dm_only)
  end

end

app/views/notes/_form.html.haml
= simple_form_for(@note, wrapper: :vertical_form, html: {role: "form"}, wrapper_mappings: {select: :vertical_select, boolean: :vertical_boolean}) do |f|
  = f.error_notification

  %fieldset
    = f.input :name
    = f.input :text, input_html: {rows: 10}
    - unless @note.new_record?
      = f.input :permalink
    = f.input :dm_only, label: "DM only"

    = f.button :submit, "Update", class: "btn-primary"
    = link_to "Cancel", @note.new_record? ? notes_path : @note, class: "btn btn-link"

app/views/notes/edit.html.haml
- model_class = Note
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/notes/index.html.haml
.page-header
  %h1.title Notes

.row
  - @notes.in_groups(3, false) do |group|
    .col-md-4
      %ol{start: 1+@notes.index(group.first).to_i}
        = list_of(group) do |note|
          = link_to(note) do
            = note.name



= content_for(:sidebar) do
  - if can?(:create, Note)
    %li
      %h4
        Actions
      %ul.nav
        %li
          = link_to(new_note_path, accesskey: "n") do
            = fa_icon("plus")
            New Note

app/views/notes/new.html.haml
- model_class = Note
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/notes/show.html.haml
.page-header
  %h1.title
    = @note.name
    = context_icon(@note)

= render_wiki(@note.text, current_user, @note)

= content_for(:title) do
  = @note.name

= content_for(:sidebar) do
  %li
    %h4 Changes
    %table.note-changes
      - if can? :manage, @note
        %tr
          %th Created:
          %td
            %span{title: @note.created_at.year}
              = @note.created_at.to_s(:short)
      %tr
        %th Updated:
        %td
          %span{title: @note.updated_at.year}
            = @note.updated_at.to_s(:short)

- if can?(:update, Note) || can?(:destroy, Note)
  = content_for(:sidebar) do
    %li
      %h4 Actions
      %ul.nav
        - if can?(:update, Note)
          %li
            = link_to(edit_note_path(@note), accesskey: "e") do
              = fa_icon("pencil")
              Edit
        - if can?(:destroy, Note)
          %li
            = link_to(note_path(@note),
                      :method => :delete,
                      :class => "action-danger",
                      :data => {:confirm => "Are you sure?"}) do
              = fa_icon("times")
              Delete

- if signed_in? && current_user.dm?
  = content_for(:sidebar) do
    %li
      %h4
        View As…
      %ul.nav
        %li
          %a{href: "#", rel: "wiki_toggle", data: {target: []}} DM
        %li
          %a{href: "#", rel: "wiki_toggle", data: {target: ["dm"]}} Veil pass
        %li
          %a{href: "#", rel: "wiki_toggle", data: {target: ["vp", "dm"]}} Anonymous