config/routes.rb
Wd::Application.routes.draw do
  resource :home
  devise_for :users

  resources :subjects do
    resources :comments
  end
  resources :notes
  resources :veil_passes, :users
  resource :searches
  resources :tags

  root :to => "homes#show"
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  include Rails.application.routes.url_helpers

  acts_as_commentable
  acts_as_taggable

  has_permalink

  validates :name, uniqueness: true, presence: true, format: {with: /\A[a-z0-9]/i}
  validates :permalink, :uniqueness => true, :presence => true
  validates :text, :presence => true

  class_attribute :specifier

  has_many :attachments, :dependent => :destroy
  accepts_nested_attributes_for :attachments, :allow_destroy => true, :reject_if => proc {|attributes| attributes["id"].blank? && attributes["attachment"].blank? && attributes["remote_attachment_url"].blank?}

  has_many :veil_passes, :dependent => :destroy
  accepts_nested_attributes_for :veil_passes, :allow_destroy => true, :reject_if => proc {|attributes| attributes["id"].blank? && attributes["user_id"].blank?}

  has_many :authorized_users, :through => :veil_passes, :source => :user

  before_save :update_vp_text, :if => :text_changed?
  before_save :update_anon_text, :if => :text_changed?


  def self.url_for(name)
    lookup(name).url
  end

  def self.lookup(name)
    s = where(name: name)
    s.first || dummy(name)
  end

  def to_param
    self.permalink
  end

  def url
    new_record? ? new_subject_path(subject: {name: name}) : url_for(self)
  end


  # def self.specifier_to_class(specifier)
  #   self.specifier == specifier ? self.name : nil
  # end

  def authorized_user?(user)
    authorized_users.include?(user)
  end


  private

  def self.dummy(name)
    Subject.new(name: name)
  end

  def update_vp_text
    self.vp_text = PrivateStache.render(text, true, false)
  end

  def update_anon_text
    self.anon_text = PrivateStache.render(text, true, true)
  end

end

app/controllers/subjects_controller.rb
# coding: utf-8
class SubjectsController < ApplicationController
  load_resource :find_by => :permalink
  authorize_resource
  before_filter :check_for_redirect, only: :show
  after_filter :track, :only => :show


  def create
    if @subject.save
      redirect_to @subject, notice: "Subject created"
    else
      render :new
    end
  end

  def destroy
    @subject.destroy
    redirect_to({action: "index"}, alert: "Subject destroyed")
  end

  def edit
  end

  def index
    @subjects = @subjects.order("regexp_replace(name, '^(the|an?) ', '', 'i') ASC")
  end

  def new
  end

  def show
    abil = Ability.new(current_user)
    @attachments = @subject.attachments.accessible_by(abil)
    @veil_passes = @subject.veil_passes.accessible_by(abil)
  end

  def update
    if @subject.update(subject_params)
      redirect_to @subject, notice: "Subject updated"
    else
      render :edit
    end
  end


  protected

  NUM_RECENT_SUBJECTS = 9

  def track
    session[:recent_subjects] = session[:recent_subjects]
      .find_all {|id, time| id != @subject.id}
      .take(NUM_RECENT_SUBJECTS)
    session[:recent_subjects].unshift([@subject.id, Time.now])
  end


  def subject_params
    params
      .require(:subject)
      .permit(:name, :text, :permalink, :dm_only, :tag_list,
              {veil_passes_attributes: [:id,
                                        :subject_id,
                                        :user_id,
                                        :includes_attachments,
                                        :_destroy]},
              {attachments_attributes: [:id,
                                        :attachment,
                                        :remote_attachment_url,
                                        :attachment_cache,
                                        :caption,
                                        :dm_only,
                                        :_destroy]})
  end

  def check_for_redirect
    if /\Aredirect: (.+)$/ === @subject.text.strip
      redirect_to Subject.lookup($~[1]), notice: "Redirected from “#{view_context.sanitize(@subject.name)}”".html_safe
      logger.info("Redirecting to \"#{$~[1]}\"")
      false
    end
  end

end

app/views/subjects/_form.html.haml
= simple_form_for(@subject, wrapper: :vertical_form, html: {role: "form"}, wrapper_mappings: {select: :vertical_select, boolean: :vertical_boolean}) do |f|
  = f.error_notification

  %fieldset
    = f.input :name
    = f.input :text, input_html: {rows: 10}
    - unless @subject.new_record?
      = f.input :permalink
    = f.input :dm_only, label: "DM only"

  %fieldset
    %legend Attachments
    = f.simple_fields_for :attachments,
                          wrapper_mappings: {boolean: :vertical_boolean} do |ff|
      = ff.label :_destroy do
        - if ff.object.image?
          .thumbnail{style: "margin-bottom: -5px"}
            = image_tag(ff.object.attachment.url("micro"))
        - else
          = File.basename(ff.object.attachment.path)
      = ff.input :caption
      = ff.input :dm_only, label: "DM only"
      = ff.input :_destroy, as: :boolean, label: "Delete"

    = f.simple_fields_for(:attachments,
                          @subject.attachments.new,
                          wrapper_mappings: {boolean: :vertical_boolean}) do |ff|
      = ff.input :attachment, as: :file, wrapper: :vertical_file_input, label: "New attachment"
      = ff.input :remote_attachment_url, label: "Attachment URL"
      = ff.input :caption
      = ff.input :dm_only, label: "DM only"

  %fieldset
    %legend Veil Passes
    = f.simple_fields_for :veil_passes,
                          wrapper_mappings: {boolean: :vertical_boolean} do |ff|
      = ff.label ff.object.user_name, class: "text-capitalize"
      = ff.input :includes_attachments, as: :boolean
      = ff.input :_destroy, as: :boolean, label: "Delete"

    = f.simple_fields_for :veil_passes,
                          @subject.veil_passes.new,
                          wrapper_mappings: {boolean: :vertical_boolean} do |ff|
      = ff.input :user_id, collection: veil_pass_user_ids, include_blank: true, label: "New Veil Pass"
      = ff.input :includes_attachments

  %fieldset
    %legend Tags
    = f.input :tag_list

    = f.button :submit, "Update", class: "btn-primary"
    = link_to "Cancel", @subject.new_record? ? subjects_path : @subject, class: "btn btn-link"

app/views/subjects/edit.html.haml
- model_class = Subject
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/subjects/index.html.haml
.page-header
  %h1.title Subjects

.row
  - @subjects.in_groups(3, false) do |group|
    .col-md-4
      %ol{start: 1+@subjects.index(group.first).to_i}
        = list_of(group) do |subject|
          = link_to(subject) do
            = subject.name



= content_for(:sidebar) do
  - if can?(:create, Subject)
    %li
      %h4
        Actions
      %ul.nav
        %li
          = link_to(new_subject_path, accesskey: "n") do
            = fa_icon("plus")
            New Subject

= render "selected_tags_links"

app/views/subjects/new.html.haml
- model_class = Subject
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/subjects/show.html.haml
.page-header
  %h1.title
    = @subject.name
    = context_icon(@subject)

= render_wiki(@subject.text, current_user, @subject)

.row
  .col-md-6
    %h4 Comments
    - @subject.comments.each do |comment|
      %blockquote.comment
        %p= comment.comment
        %footer
          %cite
            %span.short-name<>
              = comment.user_short_name
            %em
              = time_ago_in_words(comment.created_at).capitalize
              ago.
    - unless @subject.comments.present?
      %em No comments found

  .col-md-6
    %h4 Add your comment
    - if user_signed_in?
      = render partial: "comments/form"
    - else
      = link_to("Sign in", new_user_session_path)
      to comment.

= content_for(:title) do
  = @subject.name


= content_for(:sidebar) do
  - if @attachments.present?
    %li
      %h4 Attachments
      %ul.nav
        -# Use @attachments, which is restricted by dm only / veil passes
        = list_of(@attachments) do |attachment|
          .thumbnail
            - if attachment.image? # TODO set default url
              = attachment_image_overlay(attachment) do
                = link_to(attachment.attachment.url) do
                  = image_tag(attachment.attachment.thumb.url)
            .caption
              %div
                = link_to(attachment.attachment.url) do
                  = attachment.caption
                - unless attachment.image?
                  = context_icon(attachment)
              %div
                = attachment_metadata(attachment)

  %li
    %h4 Changes
    %table.subject-changes
      - if can? :manage, @subject
        %tr
          %th Created:
          %td
            %span{title: @subject.created_at.year}
              = @subject.created_at.to_s(:short)
      %tr
        %th Updated:
        %td
          %span{title: @subject.updated_at.year}
            = @subject.updated_at.to_s(:short)

  - if @subject.tags.present?
    %li
      %h4 Tags
      %ul.list-inline.tags-list
        = list_of @subject.tags do |tag|
          = link_to(tag_path(tag)) do
            = fa_icon("tag")
            = tag

-# Use @veil_passes, which is properly restricted by authorization
- if @veil_passes.present?
  = content_for(:sidebar) do
    %li
      %h4 Veil Passes
      %ul.nav
        = list_of(@veil_passes.joins(:user).order("users.first_name, users.last_name")) do |vp|
          .nav-text
            = vp.user_name
            - if vp.includes_attachments
              %abbr{rel: "tooltip", title: "This veil pass includes attachments."}
                = fa_icon("paperclip")

- if can?(:update, Subject) || can?(:destroy, Subject)
  = content_for(:sidebar) do
    %li
      %h4 Actions
      %ul.nav
        - if can?(:update, Subject)
          %li
            = link_to(edit_subject_path(@subject), accesskey: "e") do
              = fa_icon("pencil")
              Edit
        - if can?(:destroy, Subject)
          %li
            = link_to(subject_path(@subject),
                      :method => :delete,
                      :class => "action-danger",
                      :data => {:confirm => "Are you sure?"}) do
              = fa_icon("times")
              Delete

- if current_user.dm?
  = content_for(:sidebar) do
    %li
      %h4
        View As…
      %ul.nav
        %li
          %a{href: "#", rel: "wiki_toggle", data: {target: []}} DM
        %li
          %a{href: "#", rel: "wiki_toggle", data: {target: ["dm"]}} Veil pass
        %li
          %a{href: "#", rel: "wiki_toggle", data: {target: ["vp", "dm"]}} Anonymous